apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity
  namespace: roboshop
  labels:
    name: roboshop
    env: development
spec:
  replicas: 1
  selector:
    matchLabels:
      name: roboshop
      env: development
  template:
    metadata:
      labels:
        name: roboshop
        env: development
    spec:
      containers:
      - name: nginx
        image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node1
                  operator: NotIn
                  values: 
                  - four
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: NotIn
                  values: 
                  - us-east-1b 